### ISSUE TITLE
[list2node]显示错误

### ISSUE THREAD

**Issue by jiajiala** [any-block/obsidian-any-block#109]
![image](https://github.com/user-attachments/assets/fd0624fc-763c-40eb-9364-ee16ed865e42)
将 | 作为了层级显示
导致看的时候层级错误，以为 黄河 长江 淮河  是父子关系
实际上是并列关系

**Comment by LincZero** [comment]
预期设计，并列关系应该用 `/` 吧，真要使用 `|` 那后面不应该加空格

**Comment by jiajiala** [comment]
但这完全没道理…，md已经让类似这种（_xx_）的好多写法不能写了
每个插件都规定一些用法，那ob里的文件就越来越没法写了

**Comment by LincZero** [comment]
话说表格的单元格你也不能这样写，node的节点和表格单元格都不能这样写。所以我认为一个 “项” 不应该被写成 `... | ...` 的形式是合理且统一的。

你看作项是表格单元格就可以了。

---

这个语法是单叉的语法糖来的，必要性非常大

```
[table或lt或dir等……]

- a | b | c
- d | e | f
- g | h
  - i
  - j
```

主要是除了多叉分支外，单叉分支也非常多，必须要有一个单叉分支的语法糖。

**Comment by jiajiala** [comment]
@LincZero 

![Image](https://github.com/user-attachments/assets/334b0fb8-985b-4c16-9d2b-0ccb9752d262)
别名的|也会被识别为层级关系……这就导致很多错误
希望能够有办法关闭将“|”当做层级关系

**Comment by LincZero** [comment]
插件文件夹 data.json 文件能改内联切分符的正则

默认是：

- `|`或中文符号 + 空格
- 英文符号 + 两空格

不过话说一般双链的别名 `|` 后面 没有空格吧，一般没这种情况

**Comment by jiajiala** [comment]
谢谢，我试试

**Comment by LincZero** [comment]
![Image](https://github.com/user-attachments/assets/be759840-3c61-462e-9a1d-8d9806dbc25b)

**Comment by jiajiala** [comment]
谢谢大佬！
