### ISSUE TITLE
有可能在 obsidian 导出的PDF中正常显示 any block 块吗？

### ISSUE THREAD

**Issue by YiwangHuang** [any-block/obsidian-any-block#112]
obsidian导出的PDF中，anyblock块不能正常渲染

![image](https://github.com/user-attachments/assets/5350e871-4472-4b62-a0ac-3800a24c14f5)

**Comment by LincZero** [comment]
see #93 for detail

**Comment by YiwangHuang** [comment]
现在功能已经很强大了，这个功能需求也不是特别紧迫，慢慢来。

**Comment by LincZero** [comment]
关闭重复问题，该议题相关问题可以在 discussions 那边统一讨论
