### ISSUE TITLE
[feature request] transpose of list2ut please

### ISSUE THREAD

**Issue by hyperphysin** [any-block/obsidian-any-block#114]
list2ut converts this
![Screenshot 2024-12-24 at 6 24 27 PM](https://github.com/user-attachments/assets/90994823-41e8-4512-8e9f-d741cb9bb527)

to this
![Screenshot 2024-12-24 at 6 24 38 PM](https://github.com/user-attachments/assets/aee4b99b-d533-47f5-8fa1-5eae0e4ee966)

Could you please add a function to convert the list to this?
![Screenshot 2024-12-24 at 6 24 32 PM](https://github.com/user-attachments/assets/c7795ac1-102b-42bc-970d-fcd69d1cf9fa)

**Comment by LincZero** [comment]
![图片](https://github.com/user-attachments/assets/3a8eb68c-5958-4da0-8a80-ccab673cc3c5)
