### ISSUE TITLE
[bug] 3.1.2 ![]嵌入含有anyblock的页面会导致页面一直闪烁刷新

### ISSUE THREAD

**Issue by DZL1943** [any-block/obsidian-any-block#56]
<img width="1016" alt="图片" src="https://github.com/user-attachments/assets/9689765e-1c7d-4b9a-a88c-3b542a05007a">

**Comment by LincZero** [comment]
插件冲突吗？这个报错是 floating-toc 给的

**Comment by LincZero** [comment]
DZL1943 的补充：

<img width="1023" alt="369310001-9aeae943-8538-4351-88d0-1af446bbe08a" src="https://github.com/user-attachments/assets/b39e265d-e040-443c-acc4-5dd1bba0b2f4">

但缺少md源码，无法复现

**Comment by DZL1943** [comment]
<img width="978" alt="图片" src="https://github.com/user-attachments/assets/e2a75184-79c9-4b5c-b33f-0d95bf666862">

**Comment by LincZero** [comment]
![图片](https://github.com/user-attachments/assets/356957f1-fa25-4ebf-8422-9c4158fe3e00)

我并没有复现，包括没有看到页面闪烁以及控制台报错

**Comment by LincZero** [comment]
建议开一个空仓库只安装anyblock插件查看是否能够复现这一问题，排除插件或主题冲突

**Comment by DZL1943** [comment]
https://github.com/user-attachments/assets/fcf51960-ab59-4997-8a3c-95ced81584d9

**Comment by LincZero** [comment]
![图片](https://github.com/user-attachments/assets/b4d60ca5-6ccf-41dd-a09c-23ce45091345)

还是复现不了……还是建议你新开一个新仓库，里面除乐AnyBlock以外什么插件都不要装，来试。

如果还是出现这个问题，把这个仓库压缩后发过来。毕竟没办法复现我就没办法定位到错误和修复

**Comment by DZL1943** [comment]
[obsidian-test-vault.zip](https://github.com/user-attachments/files/17083450/obsidian-test-vault.zip)

**Comment by LincZero** [comment]
我这打开没有问题，Ob版本问题？或者在MacOS版本有问题？

**Comment by DZL1943** [comment]
<img width="801" alt="图片" src="https://github.com/user-attachments/assets/fce105c5-1f9d-4240-b91d-b5f2be7fdbde">

**Comment by DZL1943** [comment]
如果复现不了, 建议先用一个相对复杂的内容(多行多列)去触发, 多刷新、打开几次.

**Comment by PlayerMiller109** [comment]
@DZL1943 我用你的方法，只要含有 Anyblock 引用的文档处于阅读模式，不论是从编辑模式切到阅读模式，还是打开的时候就是阅读模式，可以稳定复现，Win11 v1.6.7，Anyblock v3.1.7。但我也确实不知道为啥。总之我也打包一个库发上来吧。
[test-anyblock-3.1.7.zip](https://github.com/user-attachments/files/17610090/test-anyblock-3.1.7.zip)

<img width="500" src="https://github.com/user-attachments/assets/25d9b4fe-355d-48db-920d-60ce0ef77320">

```
SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.7.4
	Operating system: Windows 11 Home China 10.0.22631
	Login status: not logged in
	Language: zh
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: AnyBlock v3.1.7

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by LincZero** [comment]
@PlayerMiller109  你这个能复现

**Comment by LincZero** [comment]
应该修好了，可以在这里下载： https://github.com/any-block/obsidian-any-block/actions/runs/11652057541
改的地方有点怕有其他问题，先不传正式版本
