### ISSUE TITLE
建议：希望把 [mdMindmap] / [md思维导图] / [md脑图] 添加全屏功能

### ISSUE THREAD

**Issue by HeiMaoJingZhangGiaoGe** [any-block/obsidian-any-block#82]
mdMindmap可以很好的渲染markdown语法，添加在笔记头部，可以把全篇笔记变成md思维导图，但是现在只能是在一个小窗口部分查看，虽然能放大，但是很不方便。

虽然Obsidian插件中有一个叫做“Mind Map”的，但是其功能只能查看全篇笔记，无法局部嵌入查看。

希望后期有全屏功能，感谢开发者的贡献！

**Comment by LincZero** [comment]
## 通用解决方案

其实图表类的图，都有类似的需求。
比如说原生的mermaid，或者说plantuml插件，其渲染出来的图表可能都有需要放大全屏查看的需求。
我认为做了一个通用插件去解决他们，会是一个好主意。

https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/docs/zh/05.%20%E7%B2%BE%E5%BD%A9%E7%94%A8%E4%BE%8B.html#diagram-zomm-drag

对于向list2node这类本身不支持拖拽的渲染结果，可以额外提供局部的缩放和拖拽

![image](https://github.com/user-attachments/assets/95058c46-1c05-4e17-8e61-4266a3be4b58)

对于渲染内容较多，在小区域显示不方便的渲染结果，点右上角的 “全屏” 按钮也能提供放大的编辑体验

![image](https://github.com/user-attachments/assets/558002b0-9cd0-4831-aec7-58861e063d2a)

插件可以通过在设置中填写选择器，自由选择任意div元素

不过也许有些bug……你用了就知道了……问题去找那边的作者反馈。我也和该插件的开发者认识，有时间我也可能过去PR一下

**Comment by LincZero** [comment]
## 通用方案2

上面那个应用商店有，还有一个应用商店没有的，要用BRAT下载的：

https://github.com/gitcpy/obsidian-diagram-pop/tree/main

我更推荐，更精简些，bug少点。主要是没那么影响默认体验，性能损耗没那么大。刚开始说的那个我总感觉性能比较大

**Comment by HeiMaoJingZhangGiaoGe** [comment]
感谢说明！通过第一个插件添加选择器`.ab-replaceEl`后，达到的效果大体上还可以
