### ISSUE TITLE
[feat] `::: info` 支持自定义标题

### ISSUE THREAD

**Issue by NipGeihou** [any-block/obsidian-any-block#83]
我是一个obsidian新手，正在尝试使用obsidian来管理基于vuepress的博客内容，通过`Any Block`插件后文章中的vuepress“自定义容器”正常显示，但如果使用了自定义标题则会丢失了样式。

正常显示：
```md
::: tip
这是一个提示
:::
```

无法正常显示：
```md
::: danger STOP
危险区域，禁止通行
:::
```

[Markdown Extensions | VuePress](https://v1.vuepress.vuejs.org/guide/markdown.html#custom-containers)

**Comment by LincZero** [comment]
未支持，可以支持

在未支持之前，这里给点临时方案：

## callout/alert语法

obsidian人惯用的callout/alert语法：

（obsidian的人一般都是用这种语法的。可以在vuepress中安装mdit插件markdown-it-obsidian-callout插件以在vuepress中支持该语法）

> [!note]
> 例如这样
> ```
> > [!note] title
> > content
> ```

## 使用引用块处理器

````md
::: add([!note] title)|quote
content
:::
````

**Comment by NipGeihou** [comment]
> 未支持，可以支持
> 
> 在未支持之前，这里给点临时方案：
> 
> ## callout/alert语法
> obsidian人惯用的callout/alert语法：
> 
> （obsidian的人一般都是用这种语法的。可以在vuepress中安装mdit插件 `markdown-it-obsidian-callout` 以在vuepress中支持该语法）
> 
> Note
> 
> 例如这样
> 
> ```
> > [!note] title
> > content
> ```
> 
> ## 使用引用块处理器
> ```
> ::: add([!note] title)|quote
> content
> :::
> ```

感谢您的临时方案，已安装`markdown-it-obsidian-callout`在新的文章中使用，效果很棒，同时期待对`::: info title`的支持，使得在旧文章也能正常显示。
