### ISSUE TITLE
[bug] 预览模式下闪屏

### ISSUE THREAD

**Issue by anranyang** [any-block/obsidian-any-block#84]
ob v1.7.4

win 11

预览模式下一直闪
![动画](https://github.com/user-attachments/assets/d0d3421f-d68d-4056-bb80-34fc82c7ca20)

**Comment by LincZero** [comment]
比较类似的问题在 #56

你这里看起来安装了挺多插件和主题，最好能排除一下是什么引起的。
可能是文章的特定某几行或者库里的某几个插件导致的

**Comment by DZL1943** [comment]
终于有人也发现这个问题了

**Comment by DZL1943** [comment]
顺便提醒下, 3.1.1貌似是正常的, 可以重点关注下3.1.2的修改.

**Comment by LincZero** [comment]
我还是没法复现，但你说3.1.2引起的……我看了下，暂时怀疑这里：

![图片](https://github.com/user-attachments/assets/d3826c81-1648-4d9c-af4d-235e4d048f71)

这里的是检测到你修改了md内容后，然后切换到阅读模式后，强行刷新一次阅读模式的页面（避免由于缓存而引起阅读模式没有实时更新）

除非检测，但按理说也不会一直一直刷新（除非认为你的md内容一直在变，我不知道这是什么导致的，因为我这边压根复现不了）

---

具体是不是这种情况呢？由于我这复现不出来，你们可以帮忙看一下这个：

插件文件夹下有个 data.json 文件，里面有一个项默认是 `"is_debug": false`，把false改成true并重启插件……此时控制台应该会有额外的打印。

看一下阅读模式一直在闪的情况下，是不是控制台一直刷，并且 `Local cache present, perform a global refresh (rebuildView)` 这个语句会混杂在其中一直输出

**Comment by DZL1943** [comment]
<img width="1007" alt="图片" src="https://github.com/user-attachments/assets/c14951ee-a349-4d0e-adcc-04c5fc6410ab">

**Comment by LincZero** [comment]
是每次切换视图，他会出来五六行，还是debug信息一直刷屏？

我把强制刷新的代码行删了，编译一份：（缺点是实时模式编辑完anyblock块后，再切换阅读模式，可能会由于ob的缓存策略存在渲染错位的问题）

[main.zip](https://github.com/user-attachments/files/17541459/main.zip)

**Comment by PlayerMiller109** [comment]
试下下面这个，在编辑模式修改一下，还没产生缓存的时候后立刻切阅读模式。会卡死，记得沙箱里测。

```js
const ob = require('obsidian')
module.exports = class extends ob.Plugin {
  onload() {
    const { app } = this
    this.registerMarkdownPostProcessor(async ()=> await app.workspace.activeLeaf?.rebuildView())
    // app.workspace.on('layout-change', ()=> {}) is the same.
    app.workspace.on('active-leaf-change', (leaf)=> console.log(leaf))
  }
  onunload() {}
}
```

**Comment by LincZero** [comment]
> 试下下面这个，在编辑模式修改一下，还没产生缓存的时候后立刻切阅读模式。会卡死，记得沙箱里测。

没试，不过看起来就是无限触发了吧。一个文档会触发多次 registerMarkdownPostProcessor 的（一个段落、列表、表格、标题等，都会触发一次，文档中有多少个这种元素就会触发多少次）。然后才刚开始触发第一段，你就让ob重新渲染……

具体的触发情况可以开anyblock的debug模式，控制台会打印这个环节。

**Comment by LincZero** [comment]
## 稳定复现方法

反正我一直没有触发过这个bug，直到昨天，我才找到了一个可以稳定触发的方法 —— 在预览模式Ctrl+鼠标悬浮显示悬浮内容

![图片](https://github.com/user-attachments/assets/5e298332-0ec1-437f-9f76-592bb2d9d412)

现在能稳定复现了，应该就可以修了。之前是因为我无法复现，所以拖了比较久

## 原因分析

**两个页面位于同一 Leaf 时**，能够稳定触发。
   原因是两个文件的后处理器被依次触发，而文件A到文件B的过程必触发之前判断的 “文件内容修改”，而Leaf的刷新会同时影响两个文件，导致无限刷新。

## 解决方案

之前缓存的文件内容只是一个全局变量，修改之，变为与文件路径绑定的一个map变量。
即只有某一文件的内容发生修改，才会触发更新。从A文件的后处理器到B文件的后处理器这个过程，虽然后处理器对应的文件内容修改了，但文件路径也修改了。便不会触发更新

**Comment by LincZero** [comment]
应该修好了，可以在这里下载： https://github.com/any-block/obsidian-any-block/actions/runs/11652057541
改的地方有点怕有其他问题，先不传正式版本
