### ISSUE TITLE
请问大佬这个格式有没有终止符？就是上半段脑图，下半段文字，中间有办法隔开吗？

### ISSUE THREAD

**Issue by kiradzS** [any-block/obsidian-any-block#85]
我只知道[]之间填上需要的格式，但是没找到终止格式的符号

**Comment by LincZero** [comment]
早上好，可以的

选择器相关文档： https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/docs/zh/03.%20%E9%80%89%E6%8B%A9%E5%99%A8.html

**Comment by LincZero** [comment]
如果问题未能解决，或依然持有疑问，欢迎再次打开该issue
