### ISSUE TITLE
Pandoc Export Support

### ISSUE THREAD

**Issue by MinaMatta98** [any-block/obsidian-any-block#86]
Hello,

Would you consider pandoc support for exporting to PDF's/external formats?

This would work nicely with the obsidian-pandoc plugin.

**Comment by LincZero** [comment]
#62 I mentioned this problem before, but it was in Chinese before, I tried to translate the content (please forgive me for the bad translation, mainly for machine translation).

**Comment by LincZero** [comment]
If I can solve your problem, I will close the issue and keep only '#62'.

If you have any more suggestions, you are welcome to submit them in '#62'

**Comment by LincZero** [comment]
Due to the same problem, it will be closed. If there are any more problems, please open it again.
