### ISSUE TITLE
Disable reading mode example dropdown?

### ISSUE THREAD

**Issue by BogdanCodreanu** [any-block/obsidian-any-block#96]
Hello, is there a way to disable the reading mode - dropdown of examples?

![image](https://github.com/user-attachments/assets/c79256c1-6152-4cbd-9cb1-12b8d2251031)

**Comment by LincZero** [comment]
You can use css to set the corresponding element 'display:none'.

If you can't, do you need me to help you write the corresponding css fragments and guide you to configuration?

**Comment by BogdanCodreanu** [comment]
That was a great idea! It hadn't crossed my mind. Thank you for the suggestion. For anyone, I used 
```
.markdown-reading-view {
  select.ab-button.ab-button-2.edit-block-button {
    display: none;
  }
}
```
