### ISSUE TITLE
【bug】白板中若存在多个带any-block的笔记会无限闪烁

### ISSUE THREAD

**Issue by wql201** [any-block/obsidian-any-block#97]
不知什么bug触发视图无限重新渲染了

白板视野中只有单个笔记，渲染正常，多个就不行了

**Comment by LincZero** [comment]
尝试使用这个版本的anyblock：

https://github.com/any-block/obsidian-any-block/actions/runs/11652057541

（需要烦请手动下载）

**Comment by LincZero** [comment]
近期修复过，但由于涉及代码重构（有bug风险），在被反馈稳定之前不会发布正式版本

**Comment by wql201** [comment]
十分感谢！
白板中的问题解决了，同时又发现2处bug
![PixPin_2024-11-08_22-06-36](https://github.com/user-attachments/assets/b053ca10-4320-4897-9efc-5f0bfd887083)

1. 实时浏览视图下，![[]] 未正确渲染全部内容，上部分缺失
2. 对![[]] 使用Ctrl开启悬浮预览窗口异常，会触发当前笔记重新渲染，并且浮预览窗口中的any-block文本未正确渲染成图表

辛苦大佬辛勤开发😘

**Comment by LincZero** [comment]
https://github.com/any-block/obsidian-any-block/actions/runs/11754494402 已修复第一点

第二点如果笔记内置片段没有被渲染过或检测到内容修改过，是会有一次强制刷新保证渲染正确，后续再悬浮显示应该不会再有这种问题。不过按理说应该都是能正确渲染的，不知道你说的未正确渲染图表是什么情况

**Comment by LincZero** [comment]
这个issue内容太多了，鉴于白板闪烁问题的解决、以及实时使用 `![[]]` 导致20px的内容缺失的问题，已经解决，将关闭该issue。

如果有其他问题，希望新开issue单独讨论
